title: "HireGen Documentation"
description: "An advanced recruitment platform designed to streamline the hiring process for employers and jobseekers."
theme: jekyll-theme-minimal

# Optional settings
show_downloads: false
github:
  is_project_page: false
